### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by florian-rabe** [UniFormal/mmt_jupyter_kernel#1]
@tkw1536 Can you rename the repo, e.g., into Jupyter or Jupyter-kernel.

The current name would be confusing to MMT users.

**Comment by tkw1536** [comment]
Jupyter Kernel is too generic for Jupyter users. How about jupyter-mmt-kernel or something similar?

**Comment by tkw1536** [comment]
I got no answer, so I have renamed the repository to `mmt_jupyter_kernel`. Closing issue.
