### ISSUE TITLE
README is wrong

### ISSUE THREAD

**Issue by jdemeyer** [UniFormal/mmt_jupyter_kernel#2]
1. Is the package called `mmt_kernel` or `mmt_jupyter_kernel`? Both names are used in the README.

2. I don't find the package on PyPI, despite what the README says.

3. It should be clearly documented that the package works on Python 3 only.

**Comment by kaiamann** [comment]
I modified the README, hope everything is a bit clearer now. If not feel free to ask.

**Comment by tkw1536** [comment]
This issue seems to be solved now, closing.
